# Generated by Django 4.2.20 on 2025-04-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datingprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dating Profile', 'verbose_name_plural': 'Dating Profiles'},
        ),
    ]
