# Generated by Django 4.2.20 on 2025-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0003_chatroom_created_at_chatroom_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
