# Generated by Django 4.2.20 on 2025-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Weight'),
        ),
    ]
