# Generated by Django 4.2.20 on 2025-04-11 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0002_character_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='content_preferences',
        ),
        migrations.RemoveField(
            model_name='character',
            name='views',
        ),
        migrations.AddField(
            model_name='character',
            name='list_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='list_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='show_in_lists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='allow_random_rp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='body_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('excited', 'Excited'), ('tired', 'Tired'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away'), ('busy', 'Busy'), ('inactive', 'Inactive')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='custom_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='private_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
