# Generated by Django 4.2.20 on 2025-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='content_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_mood',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('flirty', 'Flirty'), ('playful', 'Playful'), ('passionate', 'Passionate'), ('dominant', 'Dominant'), ('submissive', 'Submissive'), ('shy', 'Shy'), ('confident', 'Confident'), ('curious', 'Curious'), ('seductive', 'Seductive')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away'), ('busy', 'Busy'), ('inactive', 'Inactive'), ('looking', 'Looking for RP'), ('private', 'Private')], default='offline', max_length=20),
        ),
    ]
