# Generated by Django 4.2.20 on 2025-04-10 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Category Key')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bell', max_length=50, verbose_name='Font Awesome Icon')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Category Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Notification Category',
                'verbose_name_plural': 'Notification Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.CharField(choices=[('all', 'All Notifications'), ('important', 'Important Only'), ('none', 'None')], default='all', max_length=10, verbose_name='In-App Notifications')),
                ('email', models.CharField(choices=[('all', 'All Notifications'), ('important', 'Important Only'), ('none', 'None')], default='important', max_length=10, verbose_name='Email Notifications')),
                ('push', models.CharField(choices=[('all', 'All Notifications'), ('important', 'Important Only'), ('none', 'None')], default='none', max_length=10, verbose_name='Push Notifications')),
                ('sound', models.BooleanField(default=True, verbose_name='Play Sound')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='notifications.notificationcategory', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('character_like', 'Character Like'), ('character_rating', 'Character Rating'), ('character_comment', 'Character Comment'), ('character_mention', 'Character Mention'), ('user_mention', 'User Mention'), ('system', 'System Notification'), ('moderation', 'Moderation Alert')], max_length=20, verbose_name='Type')),
                ('verb', models.CharField(max_length=255, verbose_name='Verb')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('action_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('image_url', models.CharField(blank=True, max_length=255, verbose_name='Image URL')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationcategory', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'), models.Index(fields=['user', 'category'], name='notificatio_user_id_a72143_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
